# Generated by Django 2.2 on 2021-05-09 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=55)),
                ('password', models.CharField(max_length=45)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('breed', models.CharField(max_length=55)),
                ('birthdate', models.DateField()),
                ('age', models.IntegerField()),
                ('fav_food', models.TextField()),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('curr_weight', models.IntegerField()),
                ('goal_weight', models.IntegerField()),
                ('percentage', models.CharField(choices=[('.015', '1.5%'), ('.02', '2%'), ('.03', '3%'), ('.05', '5%')], default='1.5%', max_length=5)),
                ('daily_feeding', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='mainApp.User')),
            ],
        ),
    ]
