# Generated by Django 2.2 on 2021-05-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_pet_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='percentage',
            field=models.CharField(choices=[('.015', '1.5%'), ('.02', '2%'), ('.03', '3%'), ('.05', '5%')], default='1.5%', max_length=5),
        ),
    ]
